Hotel-Reservation-Manager/ViewModels/Reservations/ReservationCreateViewModel.cs
using Hotel_Reservation_Manager.Data.Models;
using Hotel_Reservation_Manager.ViewModels.Customers;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Hotel_Reservation_Manager.ViewModels.Reservations
{
    public class ReservationCreateViewModel
    {
        public string UserId { get; set; }
        public IList<Customer> Customers { get; set; } = 
            new List<Customer>();
        public int SelectedRoomCap { get; set; }
        [Required(ErrorMessage = "Please select and submit a room")]
        public string RoomId { get; set; }
        public SelectList Rooms { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [DisplayName("Accomodation date")]
        public DateTime AccommodationDate { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [DisplayName("Leave date")]
        public DateTime LeaveDate { get; set; }

        [DisplayName("Breakfast")]
        public bool HasBreakfast { get; set; }

        [DisplayName("Allinclusive")]
        public bool HasAllInclusive { get; set; }
    }
}

Hotel-Reservation-Manager/ViewModels/Reservations/ReservationDetailsViewModel.cs
using Hotel_Reservation_Manager.ViewModels.Customers;
using System;
using System.Collections.Generic;

namespace Hotel_Reservation_Manager.ViewModels.Reservations
{
    public class ReservationDetailsViewModel: ReservationIndexViewModel
    {
        public ICollection<CustomerIndexViewModel> Customers { get; set; }
    }
}

Hotel-Reservation-Manager/ViewModels/Reservations/ReservationEditViewModel.cs
using Hotel_Reservation_Manager.Data.Models;
using Hotel_Reservation_Manager.ViewModels.Customers;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Hotel_Reservation_Manager.ViewModels.Reservations
{
    public class ReservationEditViewModel: ReservationCreateViewModel
    {
        public string Id { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        [DisplayName("Accomodation date")]
        public new DateTime AccommodationDate { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        [DisplayName("Leave date")]
        public new DateTime LeaveDate { get; set; }
        public IList<Customer> CustomersToAdd { get; set; } = new List<Customer>();
        public IList<CustomerIndexViewModel> CustomersToRemove { get; set; } = new List<CustomerIndexViewModel>();
    }
}

Hotel-Reservation-Manager/ViewModels/Reservations/ReservationIndexViewModel.cs
using Hotel_Reservation_Manager.Data.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Hotel_Reservation_Manager.ViewModels.Reservations
{
    public class ReservationIndexViewModel
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public Room Room { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        [DisplayName("Accomodation date")]
        public DateTime AccommodationDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        [DisplayName("Leave date")]
        public DateTime LeaveDate { get; set; }

        [DisplayName("Breakfast")]
        public bool HasBreakfast { get; set; }

        [DisplayName("Allinclusive")]
        public bool HasAllInclusive { get; set; }

        [Display(Name = "Total price")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

    }
}

Hotel-Reservation-Manager/Controllers/ReservationsController.cs
using Hotel_Reservation_Manager.Data.Models;
using Hotel_Reservation_Manager.Services.Customers;
using Hotel_Reservation_Manager.Services.Reservations;
using Hotel_Reservation_Manager.ViewModels;
using Hotel_Reservation_Manager.ViewModels.Customers;
using Hotel_Reservation_Manager.ViewModels.Reservations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Hotel_Reservation_Manager.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class ReservationsController : Controller
    {
        private readonly IReservationsService reservationsService;
        public ReservationsController(IReservationsService reservationsService)
        {
            this.reservationsService = reservationsService;
        }
        public async Task<IActionResult> Index(ReservationsIndexViewModel model)
        {
            model = await reservationsService.GetReservationsAsync(model);
            return View(model);
<<<<<<< HEAD

=======
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
        }
        public async Task<IActionResult> Create(string roomId)
        {
            ReservationCreateViewModel model = new ReservationCreateViewModel();
            await ConfigureCreateVM(model, roomId);
            if (!model.Rooms.Any())
            {
                return RedirectToAction("Error", "Home", new ErrorViewModel() { ErrorMessage = "No free rooms at his time" });
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReservationCreateViewModel model)
        {
            //Gets current user's id
            model.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            //Remove temporary empty Customer objects
            model.Customers = model.Customers.Where(x => x.FirstName != null && x.LastName != null && x.PhoneNumber != null).ToList();

            // Check if user submitted a roomid
            if (model.RoomId==null)
            {
                ModelState.AddModelError(nameof(model.RoomId), "Please select and submit a room");
                await ConfigureCreateVM(model, model.RoomId);
                return View(model);
            }
            //Checks Accommodation and Leave date if they are sensible
            if (CheckDurationOfDates(model.LeaveDate,model.AccommodationDate))
            {
                ModelState.AddModelError(nameof(model.LeaveDate), "Leave date can't be before Accommodation Date");
                ModelState.AddModelError(nameof(model.AccommodationDate), "Accommodation Date can't be after Leave Date");
                await ConfigureCreateVM(model, model.RoomId);
                return View(model);
            }
            //Check if nubmer of people is more than room capacity
            if (await reservationsService.GetRoomCapacityAsync(model.RoomId) < model.Customers.Count)
            {
                ModelState.AddModelError(nameof(model.Customers), "Number of people exceeds Room Capacity");
                await ConfigureCreateVM(model, model.RoomId);
                return View(model);
            }
            //check if user inputed at least 1 customer
            if (!model.Customers.Any())
            {
                ModelState.AddModelError(nameof(model.Customers), "Add at least 1 person");
                await ConfigureCreateVM(model, model.RoomId);
                return View(model);
            }
            List<Customer> inputCustomers = model.Customers.Select(x => new Customer()
            {
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
            }).ToList();
            //chek every inputted User if he exists in database and if he already has a reservation
            foreach (var cust in inputCustomers)
            {
                Customer customer = await reservationsService.FindCustomerAsync(cust);
                if (customer == null)
                {
                    ModelState.AddModelError(nameof(model.Customers), $"{cust.FirstName} {cust.LastName} isn't found in the database. You have to first add him/her");
                    await ConfigureCreateVM(model, model.RoomId);
                    return View(model);
                }
                if (customer.Reservation != null)
                {
                    ModelState.AddModelError(nameof(model.Customers), $"{cust.FirstName} {cust.LastName} has already been asigned to a Reservation");
                    await ConfigureCreateVM(model, model.RoomId);
                    return View(model);
                }
            }
            if (ModelState.IsValid)
            {
                await reservationsService.CreateReservationAsync(model);
                return RedirectToAction(nameof(Index));
            }
            await ConfigureCreateVM(model, model.RoomId);
            return View(model);
        }
        public async Task<IActionResult> Details(string id)
        {
            ReservationDetailsViewModel model = await reservationsService.GetReservationDetailsAsync(id);
            if (reservationsService.HasReservationPassed(model.LeaveDate))
            {
                await reservationsService.DeleteReservationAsync(await reservationsService.GetReservationToDeleteAsync(id));
                return RedirectToAction("Error", "Home", new ErrorViewModel()
                { ErrorMessage = "Reservation has already passed and will be deleted" });
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id)
        {
            ReservationDetailsViewModel model = await reservationsService.GetReservationToDeleteAsync(id);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ReservationDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                await reservationsService.DeleteReservationAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            ReservationEditViewModel model = await reservationsService.EditReservationByIdAsync(id);
            if (reservationsService.HasReservationPassed(model.LeaveDate))
            {
                await reservationsService.DeleteReservationAsync(await reservationsService.GetReservationToDeleteAsync(id));
                return RedirectToAction("Error", "Home", new ErrorViewModel() 
                { ErrorMessage = "Reservation has already passed and will be deleted" });
            }
            return View(model);
        }
        ///<summary>POST: ReservationController/Edit/?(id)</summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ReservationEditViewModel model)
        {
            //Gets current user's id
            model.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            //Remove temporary empty Customer objects
            model.CustomersToAdd = model.CustomersToAdd.Where(x => x.FirstName != null && x.LastName != null && x.PhoneNumber != null).ToList();
            model.CustomersToRemove = model.CustomersToRemove.Where(x=>x.RemoveFromRes).ToList();

            // Check if user submitted a roomid
            if (model.RoomId == null)
            {
                ModelState.AddModelError(nameof(model.RoomId), "Please select and submit a room");
                return View(await reservationsService.EditReservationByIdAsync(model.Id));
            }
            //Checks Accommodation and Leave date if they are sensible
            if (CheckDurationOfDates(model.LeaveDate, model.AccommodationDate))
            {
                ModelState.AddModelError(nameof(model.LeaveDate), "Leave date can't be before Accommodation Date");
                ModelState.AddModelError(nameof(model.AccommodationDate), "Accommodation Date can't be after Leave Date");
                return View(await reservationsService.EditReservationByIdAsync(model.Id));
            }
            //Check if nubmer of people is more than room capacity
            if (await reservationsService.GetRoomCapacityAsync(model.RoomId) < model.CustomersToAdd.Count)
            {
                ModelState.AddModelError(nameof(model.CustomersToAdd), "Number of people exceeds Room Capacity");
                return View(await reservationsService.EditReservationByIdAsync(model.Id));
            }
            List<Customer> inputCustomers = model.CustomersToAdd.Select(x => new Customer()
            {
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
            }).ToList();
            //chek every inputted User if he exists in database and if he already has a reservation
            foreach (var cust in inputCustomers)
            {
                Customer customer = await reservationsService.FindCustomerAsync(cust);
                if (customer == null)
                {
                    ModelState.AddModelError(nameof(model.CustomersToAdd), $"{cust.FirstName} {cust.LastName} isn't found in the database. You have to first add him/her");
                    return View(await reservationsService.EditReservationByIdAsync(model.Id));
                }
                if (customer.Reservation != null)
                {
                    ModelState.AddModelError(nameof(model.CustomersToAdd), $"{cust.FirstName} {cust.LastName} has already been asigned to a Reservation");
                    return View(await reservationsService.EditReservationByIdAsync(model.Id));
                }
            }

Hotel-Reservation-Manager/Controllers/RoomsController.cs
using Hotel_Reservation_Manager.Services.Rooms;
using Hotel_Reservation_Manager.ViewModels.Rooms;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Hotel_Reservation_Manager.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class RoomsController : Controller
    {
        public IRoomsService roomsService { get; set; }
        public RoomsController(IRoomsService roomsService)
        {
            this.roomsService = roomsService;
        }
        // GET: RoomsController
        public async Task<IActionResult> Index(RoomsIndexViewModel model)
        {
<<<<<<< HEAD
            model = await this.roomsService.GetRoomsAsync(model);
=======
            model = await roomsService.GetRoomsAsync(model);
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
            return View(model);
        }

        // GET: RoomsController/Details/5
        public async Task<IActionResult> Details(string id)
        {
            RoomDetailsViewModel model = await roomsService.GetRoomDetailsByIdAsync(id);
            return View(model);
        }

        // GET: RoomsController/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoomsController/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoomCreateViewModel model)
        {
            if (roomsService.DoesRoomNumberExist(model.Number))
            {
                ModelState.AddModelError(nameof(model.Number), "There is already a room with this number");
                return View(model);
            }
            await roomsService.CreateRoomAsync(model);
            return RedirectToAction(nameof(Index));
        }

        // GET: RoomsController/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            RoomEditViewModel model = await roomsService.EditRoomByIdAsync(id);
            return View(model);
        }

        // POST: RoomsController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoomEditViewModel model)
        {         
            if (roomsService.DoesRoomNumberExist(model.Number,model.Id))
            {
                ModelState.AddModelError(nameof(model.Number), "There is already a room with this number");
                return View(model);
            }
            await roomsService.UpdateRoomAsync(model);
            return RedirectToAction(nameof(Index));
        }

        // GET: RoomsController/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            RoomDetailsViewModel model = await roomsService.DeleteRoomByIdAsync(id);
            return View(model);
        }

        // POST: RoomsController/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(RoomDetailsViewModel model)
        {
            await roomsService.DeleteConfirmRoomAsync(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

Hotel-Reservation-Manager/Views/Reservations/Create.cshtml
@model ReservationCreateViewModel

@{
    ViewData["Title"] = "Create Reservation";
}
<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="card rounded-3" style="background-color:#F0F2F5">
        <h1 class="text-center">Create Reservation</h1>
        <div class="card-body p-4 p-md-5">
            <form asp-controller="Reservations" asp-action="Create" method="get">
                <label asp-for="RoomId" class="control-label">Select Room:</label>
                <select asp-for="RoomId" asp-items="@Model.Rooms"></select>
                <span asp-validation-for="RoomId" class="text-danger" style="display:block"></span>
                <input type="submit" id="loginSubmit"/>
            </form>
            @if (Model.RoomId!=null)
            {
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="RoomId" class="form-control" />
                    <div class="form-group">
                        <label asp-for="AccommodationDate" class="control-label"></label>
                        <input asp-for="AccommodationDate" min="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" />
                        <span asp-validation-for="AccommodationDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LeaveDate" class="control-label"></label>
                        <input asp-for="LeaveDate" min="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" />
                        <span asp-validation-for="LeaveDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="HasAllInclusive" class="control-label"></label>
                        <input asp-for="HasAllInclusive" class="form-control" />
                        <span asp-validation-for="HasAllInclusive" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="HasBreakfast" class="control-label"></label>
                        <input asp-for="HasBreakfast" class="form-control" />
                        <span asp-validation-for="HasBreakfast" class="text-danger"></span>
                    </div>
                    @if (Model.SelectedRoomCap > 0)
                    {
                        <div class="form-group">
                        <h4>
                            Input existing customer Data:
                        </h4>
                        <small>(leave blank if needed)</small>
                        <div class="justify-content-center" style="margin:10px 0px 10px 0px">
                            <span asp-validation-for="Customers" class="text-danger text-center" >
                            </span>
                        </div>
                        <table class="table table-responsive table-hover "
                       style="border-radius: 10px; overflow: hidden;">
                            <thead class="thead-dark">
                                <tr>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>PhoneNumber</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < Model.SelectedRoomCap; i++)
                                {
                                    <tr>
                                        <td>
                                            <label asp-for="Customers[i].FirstName" class="control-label"></label>
                                            <input asp-for="Customers[i].FirstName" class="form-control" />
                                            <span asp-validation-for="Customers[i].FirstName" class="text-danger"></span>
                                        </td>
                                        <td>
                                            <label asp-for="Customers[i].LastName" class="control-label"></label>
                                            <input asp-for="Customers[i].LastName" class="form-control" />
                                            <span asp-validation-for="Customers[i].LastName" class="text-danger"></span>
                                        </td>
                                        <td>
                                            <label asp-for="Customers[i].PhoneNumber" class="control-label"></label>
                                            <input asp-for="Customers[i].PhoneNumber" class="form-control" />
                                            <span asp-validation-for="Customers[i].PhoneNumber" class="text-danger"></span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        </div>
                    }


                    <a asp-controller="Customers" asp-action="Create" class="btn btn-outline-primary " style="margin: 10px 0px 10px 0px;">New Customer <i class="fa-regular fa-square-plus"></i></a>
                    @if (User.IsInRole("Admin"))
                    {
                        <div>
                            <a asp-controller="Rooms" asp-action="Create" class="btn btn-outline-primary " style="margin: 10px 0px 10px 0px;">New Room <i class="fa-regular fa-square-plus"></i></a>
                    </div>
                }
                <div class="form-group text-center">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
            }
        </div>
    </div>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Hotel-Reservation-Manager/Views/Reservations/Delete.cshtml
@model ReservationDetailsViewModel

@{
    ViewData["Title"] = "Delete Reservation";
}

<h1>Are you sure you want to delete this reservation?</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Delete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                @Html.DisplayNameFor(model => model.AccommodationDate)
                @Html.DisplayFor(model => model.AccommodationDate)
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(model => model.LeaveDate)
                @Html.DisplayFor(model => model.LeaveDate)
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(model => model.HasAllInclusive)
                @Html.DisplayFor(model => model.HasAllInclusive)
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(model => model.HasBreakfast)
                @Html.DisplayFor(model => model.HasBreakfast)
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(model => model.Price)
                @Html.DisplayFor(model => model.Price)
            </div>

            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4" >
            @if (Model.Customers.Any())
        {
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Id</th>
                        <th>Email</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Adult</th>
                        <th>Phone Number</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Customers)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsAdult)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                <a asp-controller="Customers" asp-action="Details" asp-route-id="@item.Id"><i class="fa-solid fa-circle-info"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
    </table>
    }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Hotel-Reservation-Manager/Views/Reservations/Details.cshtml
@model ReservationDetailsViewModel

@{
    ViewData["Title"] = "Reservation Details";
}

<h1>Details</h1>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            @Html.DisplayNameFor(model => model.AccommodationDate)
            @Html.DisplayFor(model => model.AccommodationDate)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(model => model.LeaveDate)
            @Html.DisplayFor(model => model.LeaveDate)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(model => model.HasAllInclusive)
            @Html.DisplayFor(model => model.HasAllInclusive)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(model => model.HasBreakfast)
            @Html.DisplayFor(model => model.HasBreakfast)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(model => model.Price)
            @Html.DisplayFor(model => model.Price)
        </div>
        <div class="form-group">
            <a asp-action="Edit" asp-route-id="@Model.Id"><i class="fa-solid fa-pen-to-square"></i></a>
            <a asp-action="Delete" asp-route-id="@Model.Id"><i class="fa-solid fa-trash"></i></a>
        </div>
    </div>
    @if (Model.Customers.Any())
    {
        <div class="col-md-4">
            <h4>Customers</h4>
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Id</th>
                        <th>Email</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Adult</th>
                        <th>Phone Number</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Customers)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsAdult)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                <a asp-controller="Customers" asp-action="Details" asp-route-id="@item.Id"><i class="fa-solid fa-circle-info"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}