Hotel-Reservation-Manager/ViewModels/Shared/PagingViewModel.cs
<<<<<<< HEAD
﻿namespace Hotel_Reservation_Manager.ViewModels.Shared
{
    using System;
=======
﻿using System;

namespace Hotel_Reservation_Manager.ViewModels.Shared
{
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
    public class PagingViewModel
    {
        public PagingViewModel(int itemsPerPage = 10, string action = "Index")
        {
            this.ItemsPerPage = itemsPerPage;
            this.Action = action;
            this.Page = 1;
        }

        public int Page { get; set; }

        public bool HasPreviousPage => this.Page > 1;

        public int PreviousPageNumber => this.Page - 1;

        public bool HasNextPage => this.Page < this.PagesCount;

        public int NextPageNumber => this.Page + 1;

        public int PagesCount => (int)Math.Ceiling((double)this.ElementsCount / this.ItemsPerPage);

        public int ElementsCount { get; set; }

        public int ItemsPerPage { get; set; }

        public string Action { get; set; }
<<<<<<< HEAD
    }
}
=======

    }
}
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f

Hotel-Reservation-Manager/Controllers/CustomersController.cs
using Hotel_Reservation_Manager.Services.Customers;
using Hotel_Reservation_Manager.ViewModels.Customers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Hotel_Reservation_Manager.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class CustomersController : Controller
    {
        public ICustomersService customersService { get; set; }
        public CustomersController(ICustomersService customersService)
        {
            this.customersService = customersService;
        }
        public async Task<IActionResult> Index(CustomersIndexViewModel model)
        {
<<<<<<< HEAD
            model = await customersService.GetCustomersAsync(model);
=======
            model = await this.customersService.GetCustomersAsync(model);
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomerCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                await customersService.CreateCustomerAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Details(string id, CustomerDetailsViewModel model)
        {
            model = await customersService.GetCustomerDetailsByIdAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            CustomerEditViewModel model = await customersService.EditCustomerByIdAsync(id);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CustomerEditViewModel model)
        {
            await customersService.UpdateCustomerAsync(model);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string id)
        {
            CustomerDetailsViewModel model = await customersService.DeleteCustomerByIdAsync(id);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(CustomerDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                await customersService.DeleteConfirmCustomerAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

    }
}

Hotel-Reservation-Manager/Controllers/RoomsController.cs
using Hotel_Reservation_Manager.Services.Rooms;
using Hotel_Reservation_Manager.ViewModels.Rooms;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Hotel_Reservation_Manager.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class RoomsController : Controller
    {
        public IRoomsService roomsService { get; set; }
        public RoomsController(IRoomsService roomsService)
        {
            this.roomsService = roomsService;
        }
        // GET: RoomsController
        public async Task<IActionResult> Index(RoomsIndexViewModel model)
        {
<<<<<<< HEAD
            model = await this.roomsService.GetRoomsAsync(model);
=======
            model = await roomsService.GetRoomsAsync(model);
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
            return View(model);
        }

        // GET: RoomsController/Details/5
        public async Task<IActionResult> Details(string id)
        {
            RoomDetailsViewModel model = await roomsService.GetRoomDetailsByIdAsync(id);
            return View(model);
        }

        // GET: RoomsController/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoomsController/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoomCreateViewModel model)
        {
            if (roomsService.DoesRoomNumberExist(model.Number))
            {
                ModelState.AddModelError(nameof(model.Number), "There is already a room with this number");
                return View(model);
            }
            await roomsService.CreateRoomAsync(model);
            return RedirectToAction(nameof(Index));
        }

        // GET: RoomsController/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            RoomEditViewModel model = await roomsService.EditRoomByIdAsync(id);
            return View(model);
        }

        // POST: RoomsController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoomEditViewModel model)
        {         
            if (roomsService.DoesRoomNumberExist(model.Number,model.Id))
            {
                ModelState.AddModelError(nameof(model.Number), "There is already a room with this number");
                return View(model);
            }
            await roomsService.UpdateRoomAsync(model);
            return RedirectToAction(nameof(Index));
        }

        // GET: RoomsController/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            RoomDetailsViewModel model = await roomsService.DeleteRoomByIdAsync(id);
            return View(model);
        }

        // POST: RoomsController/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(RoomDetailsViewModel model)
        {
            await roomsService.DeleteConfirmRoomAsync(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

Hotel-Reservation-Manager/Controllers/UsersController.cs
using Hotel_Reservation_Manager.Services;
using Hotel_Reservation_Manager.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Hotel_Reservation_Manager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }
        public async Task<IActionResult> Index(UsersIndexViewModel model)
        {
            model = await usersService.GetUsersAsync(model);
            return View(model);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserCreateViewModel model)
        {          
            if (ModelState.IsValid)
            {
                await usersService.CreateUserAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        //GET: Users/Edit/(Id)
        public async Task<IActionResult> Edit(string id)
        {
            UserEditViewModel model = await usersService.EditUserByIdAsync(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                await usersService.UpdateUserAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        //GET: Users/Delete/(Id)
        public async Task<IActionResult> Delete(string id)
        {
            UserDetailsViewModel model = await usersService.DeleteUserByIdAsync(id);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(UserDetailsViewModel model)
        {
            await usersService.DeleteUserConfirmedAsync(model);
            return RedirectToAction(nameof(Index));
        }

        //GET: Users/Details/(Id)
        public async Task<IActionResult> Details(string id)
        {
            UserDetailsViewModel model = await usersService.GetUserDetailsByIdAsync(id);
            return View(model);
        }

    }
}

Hotel-Reservation-Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel Reservation Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/3c3090d0f8.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hotel Reservation Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                        @if (this.User.IsInRole("User") || this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Hotel Reservation Manager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Hotel-Reservation-Manager/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<<<<<<< HEAD
<nav aria-label="..." class="">
    <ul class="pagination  justify-content-center ">
        <li style="margin-right:5px">
            <form asp-controller="@this.Context.Request.RouteValues["controller"].ToString()" asp-action="Index" method="post">
=======

<nav aria-label="..." class="">
    <ul class="pagination  justify-content-center ">
        <li style="margin-right:5px">
            <form asp-action="@Model.Action" method="post">
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
                <select asp-for="ItemsPerPage" class="form-control border-dark" onchange="changeItemsPerPage();">
                    <option value="3">3</option>
                    <option value="10">10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                </select>
                <input type="submit" id="loginSubmit" style="visibility:hidden" />
            </form>
<<<<<<< HEAD

        </li>
        <li></li>
        <li class="page-item @if (!Model.HasPreviousPage) {
        <text>disabled</text>
}">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.PreviousPageNumber" asp-route-itemsPerPage="@Model.ItemsPerPage">
                <i class="fas fa-step-backward"></i>

=======
        </li>
        <li></li>
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.PreviousPageNumber" asp-route-itemsPerPage="@Model.ItemsPerPage">
                <i class="fas fa-step-backward"></i>
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
            </a>
        </li>
        @for (int i = Model.Page - 2; i < Model.Page; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i" asp-route-itemsPerPage="@Model.ItemsPerPage">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.Page
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.Page + 1; i <= Model.Page + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i" asp-route-itemsPerPage="@Model.ItemsPerPage">@i</a></li>
            }
        }
<<<<<<< HEAD
        <li class="page-item @if(!Model.HasNextPage){
        <text>disabled</text>
}">
=======
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
>>>>>>> 9b615d978ebcefaac978178e5eda4c713a65289f
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.NextPageNumber" asp-route-itemsPerPage="@Model.ItemsPerPage"><i class="fas fa-step-forward"></i></a>
        </li>
    </ul>
</nav>

<script type="text/javascript">
    function changeItemsPerPage() {

        console.log('Items per page changed!')

        document.getElementById('loginSubmit').click();
    }
</script>